version: '3'

services:
    web:
        build:
          dockerfile: ./docker/python/Dockerfile
          context: ./
        container_name: "flask2-web2"
        ports:
            - "5000:5000"
        volumes:
            - .:/code
